// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'ap-south-1:cdedde90-87a2-477d-a100-3ccfae28eaf7',
    'aws_cognito_region': 'ap-south-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'ecofitpartnerwebapp-hosting-mobilehub-1848118320',
    'aws_content_delivery_bucket_region': 'ap-south-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1lu7e1ps3hod2.cloudfront.net',
    'aws_mobile_analytics_app_id': '1f40f7cb8c6e43348e5913fa0e55ea4e',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '6b9a85bb-f53a-419c-9eac-da56e6f271d2',
    'aws_project_name': 'ecofit-partner-web-app',
    'aws_project_region': 'ap-south-1',
    'aws_resource_name_prefix': 'ecofitpartnerwebapp-mobilehub-1848118320',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'ap-south-1_GArAzpvgV',
    'aws_user_pools_web_client_id': '64fojsp2s5fdfqs53kqasjfm2c',
}

export default awsmobile;
